# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-blog-1:
    name: My fist job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v1
          - uses: gautamkrishnar/blog-post-workflow@v2
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/1no_pWrlHWS46fqstymCF1-OLQsnNCa7800V92dzn07dNbXEVF/?limit=15&utm_campaign=pubmed-2&fc=20240726160330" 
              max_post_count: 10
              disable_html_encoding: true

  update-readme-with-blog-2:
    name: My second job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v1
          - uses: gautamkrishnar/blog-post-workflow@v2
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/1H9AR3ZQQCaH18Wcp_iyOTZw8j_E3OKCDSUQUJEAY5iWBFeEjn/?limit=15&utm_campaign=pubmed-2&fc=20240729152954" 
              max_post_count: 10
              disable_html_encoding: true
              
     


          
