name: Update Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Platform 1 Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://pubmed.ncbi.nlm.nih.gov/rss/search/14_xQ7JEOWXCuor4N6cDMWFm9_lTOr4XdTO7hF16XqAIZakMK5/?limit=15&utm_campaign=pubmed-2&fc=20241220152958
          post_count: 10
          readme_path: ./README.md
          blog_section_start: <!-- BLOG-POST-LIST-1:START -->
          blog_section_end: <!-- BLOG-POST-LIST-1:END -->

      - name: Update Platform 2 Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://pubmed.ncbi.nlm.nih.gov/rss/search/1puh2wJZbabPSbhl6UC9oZpFmdCJ60F8rUXFF7vqC0kaw59QsO/?limit=15&utm_campaign=pubmed-2&fc=20241220153022
          post_count: 10
          readme_path: ./README.md
          blog_section_start: <!-- BLOG-POST-LIST-2:START -->
          blog_section_end: <!-- BLOG-POST-LIST-2:END -->

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update blog posts'
          git push
