# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v4
          - uses: gautamkrishnar/blog-post-workflow@v1
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/1no_pWrlHWS46fqstymCF1-OLQsnNCa7800V92dzn07dNbXEVF/?limit=15&utm_campaign=pubmed-2&fc=20240726160330,https://pubmed.ncbi.nlm.nih.gov/rss/search/10cYQ8mUsB6e5iB74FZql_dgnyCr0cfkvTgXIJh1TJnyMXi9oC/?limit=10&utm_campaign=pubmed-2&fc=20240729155617" 
              feed_names: "Spiral,Low Rank"
              template: '<a href="$url">$title</a>$newline'
              max_post_count: 10
              disable_html_encoding: true
              
     


          
